# Generated by Django 5.2.7 on 2025-10-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="photo",
            new_name="Fotografia",
        ),
    ]
